unique_ids:
  forms:
    Form1: YNPSF7KDCHVA6WWQRFYRAQGYK4N4CPVU
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: 5OSZZTA3RDWLZN57VYZ7GKEXJ5GGGT4D
    theme.css: 5XLL5D6R57DHEEKLBBNJZTNXS3PHGRFP
  scripts: {}
